name: iOS Build/Publish
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      dotnet-version-target:
        required: true
        type: string
      xcode-version:
        required: true
        type: string
      project-file:
        required: true
        type: string
      project-folder:
        required: true
        type: string
      build-config:
        required: true
        type: string
      build-version:
        required: true
        type: string
    secrets:      
      p12-cert:
        required: true
      p12-cert-password:
        required: true
      appstore-issuer:
        required: true
      appstore-keyid:
        required: true
      appstore-private-key:
        required: true
jobs:
  publish-ios:
    runs-on: macos-13
    name: iOS Publish

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        name: Set XCode version
        with:
          xcode-version: ${{ inputs.xcode-version }}
  
      - uses: actions/setup-dotnet@v2
        name: Setup .NET ${{ inputs.dotnet-version }}
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
  
      - uses: actions/checkout@v3
        name: Checkout the code
    
      # This step might be obsolete at some point as .NET MAUI workloads 
      # are starting to come pre-installed on the GH Actions build agents.
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
    
      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.project-file }}
      
      - name: Version the app
        uses: managedcode/MAUIAppVersion@v1
        with: 
          csproj: ${{ inputs.project-file }}
          version: ${{ github.run_number }} # to keep value unique
          displayVersion: '${{ inputs.build-version }}.${{ github.run_number }}'
          printFile: true # optional 
          
      - name: Publish the iOS app
        run: dotnet publish ${{inputs.project-file}} -c ${{ inputs.build-config }} -f:${{ inputs.dotnet-version-target }}-ios /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
      
  